import { Inter } from 'next/font/google'
import './global.css'
import { WebVitals } from './_components/web-vitals'

const inter = Inter({ subsets: ['latin'] })

export const BROWER_MAIN_TITLE = 'TECH BLOG'

export const metadata = {
  title: BROWER_MAIN_TITLE,
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WebVitals />
        {children}
      </body>
    </html>
  )
}
